ragflow:
  host: 127.0.0.1
  http_port: 9385
admin:
  host: 127.0.0.1
  http_port: 9381
mysql:
  name: rag_flow
  user: root
  password: infini_rag_flow
  host: localhost
  port: 3306
  max_connections: 900
  stale_timeout: 300
  max_allowed_packet: 1073741824
minio:
  user: rag_flow
  password: infini_rag_flow
  host: 127.0.0.1:9014
  bucket: ''
  prefix_path: ''
es:
  hosts: http://localhost:1200
  username: elastic
  password: infini_rag_flow
os:
  hosts: http://localhost:1201
  username: admin
  password: infini_rag_flow_OS_01
infinity:
  uri: 127.0.0.1:23817
  postgres_port: 5434
  db_name: default_db
oceanbase:
  scheme: oceanbase
  config:
    db_name: test
    user: root@ragflow
    password: infini_rag_flow
    host: localhost
    port: 2881
redis:
  db: 1
  username: ''
  password: ''
  host: localhost:6379
task_executor:
  message_queue_type: redis
user_default_llm:
  default_models:
    embedding_model:
      name: bge-m3
      factory: xxxx
      api_key: xxx
      base_url: http://localhost:6380
postgres:
  name: rag_flow
  user: rag_flow
  password: ragflow_secure_2026
  host: 127.0.0.1
  port: 5432
  max_connections: 100
  stale_timeout: 30
